app = "signet-protocol"

primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8088"

[[services]]
  http_checks = []
  internal_port = 8088
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
