route:
  receiver: default
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 12h
  routes:
    - matchers:
        - severity="critical"
      receiver: critical
      repeat_interval: 30m

receivers:
  - name: default
    # TODO: Configure real notification methods (email, webhook, Slack, etc.)
    webhook_configs:
      - url: 'http://signet:8088/alert-webhook'
        send_resolved: true
  - name: critical
    webhook_configs:
      - url: 'http://signet:8088/alert-webhook'
        send_resolved: true

inhibit_rules:
  - source_matchers: [severity="critical"]
    target_matchers: [severity="warning"]
    equal: ['alertname']
