global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/signet_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'signet-protocol'
    static_configs:
      - targets: ['signet:8088']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
