name: Dependabot Auto Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  python-tests:
    if: contains(github.head_ref, 'dependabot')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - name: Install deps
        run: |
          pip install -r requirements-dev.txt --disable-pip-version-check
      - name: Run minimal test subset
        run: |
          pytest tests/test_exchange.py -q
  n8n-node-tests:
    if: contains(github.head_ref, 'dependabot')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: integrations/n8n/package-lock.json
      - name: Install & test n8n node
        working-directory: integrations/n8n
        run: |
          npm ci || npm install
          npm test
  annotate:
    if: contains(github.head_ref, 'dependabot')
    runs-on: ubuntu-latest
    needs: [python-tests, n8n-node-tests]
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const py = '${{ needs.python-tests.result }}';
            const js = '${{ needs.n8n-node-tests.result }}';
            const summary = `Dependabot quality gate:\n- Python subset: ${py}\n- n8n node tests: ${js}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });
