name: docker-publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: vars
        run: |
          TAG="${GITHUB_REF_NAME}"
          echo "version=${TAG#v}" >> $GITHUB_OUTPUT

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/signet-protocol:${{ steps.vars.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/signet-protocol:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.version=${{ steps.vars.outputs.version }}

      - name: Security scan (Trivy)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/signet-protocol:${{ steps.vars.outputs.version }}
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        continue-on-error: true
      - name: Fail on vulnerabilities
        run: |
          if grep -qE "CRITICAL|HIGH" "$GITHUB_WORKSPACE"/trivy-results* 2>/dev/null; then
            echo "High severity vulnerabilities detected (see scan output)."; exit 1; fi || true

      - name: Smoke test container
        run: |
          docker run -d --name signet_test -p 8088:8088 ghcr.io/${{ github.repository_owner }}/signet-protocol:${{ steps.vars.outputs.version }}
          sleep 8
          curl -f localhost:8088/healthz || (echo "Health check failed" && docker logs signet_test && exit 1)
          docker rm -f signet_test
