name: lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - name: Install deps (ruff only)
        run: |
          pip install --disable-pip-version-check --no-cache-dir -r requirements-dev.txt
      - name: Ruff Lint
        run: |
          ruff check . --output-format=github
      - name: Ruff Format Check
        run: |
          ruff format --check .